### PR TITLE
Matplotlib should be a Monoid

### PR DESCRIPTION
**Pull request by fhaust**
This makes it possible to use `mconcat` and co to combine graphs:

    main = do
        onscreen $ mconcat [ axvline x | x <- [1..10] ]

    axvline x = mp # "plot.axvline(" # x ## ")"

### CODE REVIEW

**Comment by abarbu** [comment]
Good idea!

**Comment by abarbu** [comment]
Pushed 0.5.0

**Comment by fhaust** [comment]
Btw... My initial reflex was to tread `Matplotlib` like a Monad... I guess
that's possible two, but I did not look into it further.

Am 30.05.2017 5:33 nachm. schrieb "Andrei Barbu" <notifications@github.com>:

**Comment by abarbu** [comment]
The very first version actually had it as a monad. But after using it for a bit I realized that it doesn't really do anything useful as one. I at least don't compose graphs while another computation is running (but maybe others are interested in this?). And I can't really see how it would be useful as a monad transformer.

Maybe if the graph wasn't static this would make much more sense? But even then the monad wouldn't really have any interesting laws or behavior aside from passing the graph around in the background. Can you think of any interesting any monad laws or non-trivial bind for this?

**Comment by fhaust** [comment]
Not really... That was just for something like:

    forM list $ \x -> axvline x

Can be realized with Monoid just fine

Am 30.05.2017 6:00 nachm. schrieb "Andrei Barbu" <notifications@github.com>:

**Pull request merged**
